[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_flags = -Wall -Wextra

[env:tof_check]
build_src_filter = +<tof_check/>

[env:lora_check]
build_src_filter = +<lora_check/>

[env:tof_read]
build_src_filter = +<tof_read/>
build_flags = ${env.build_flags} -I include -I src/tof_read
lib_extra_dirs = vendor

[env:lora_link_a]
build_src_filter = +<lora_link/>
build_flags = ${env.build_flags} -DLORA_ROLE_A

[env:lora_link_b]
build_src_filter = +<lora_link/>
build_flags = ${env.build_flags} -DLORA_ROLE_B
